name: ortodonciainvisible
favicon: null
layout_spectrum: 0.6280649940017611
typography_spectrum: 0.3995647474657744
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.17768985382281244
  lightness: 0.01517591206356883
  saturation: 0.20046419627033174
  rhythmicContrast: 0.913177837152034
purpose: []
